apiVersion: apps/v1
kind: Deployment
metadata:
  name: instructor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instructor-app
  template:
    metadata:
      labels:
        app: instructor-app
    spec:
      containers:
        - image: instructor_service
          name: instructor-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: instructor
spec:
  type: LoadBalancer
  ports:
    - port: 8087
  selector:
    app: instructor-app